//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 12:28:12 PM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v1.contractevent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContractInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContractInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FDCP" type="{http://www.securex.be/contractevent/v1}FDCPType"/&gt;
 *         &lt;element name="contract" type="{http://www.securex.be/contractevent/v1}ContractType"/&gt;
 *         &lt;element name="paritairComite" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="employeeStatute" type="{http://www.securex.be/contractevent/v1}EmployeeStatuteType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractInfoType", propOrder = {
    "fdcp",
    "contract",
    "paritairComite",
    "employeeStatute"
})
public class ContractInfoType {

    @XmlElement(name = "FDCP", required = true)
    protected FDCPType fdcp;
    @XmlElement(required = true)
    protected ContractType contract;
    protected String paritairComite;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected EmployeeStatuteType employeeStatute;

    /**
     * Gets the value of the fdcp property.
     * 
     * @return
     *     possible object is
     *     {@link FDCPType }
     *     
     */
    public FDCPType getFDCP() {
        return fdcp;
    }

    /**
     * Sets the value of the fdcp property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDCPType }
     *     
     */
    public void setFDCP(FDCPType value) {
        this.fdcp = value;
    }

    /**
     * Gets the value of the contract property.
     * 
     * @return
     *     possible object is
     *     {@link ContractType }
     *     
     */
    public ContractType getContract() {
        return contract;
    }

    /**
     * Sets the value of the contract property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractType }
     *     
     */
    public void setContract(ContractType value) {
        this.contract = value;
    }

    /**
     * Gets the value of the paritairComite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParitairComite() {
        return paritairComite;
    }

    /**
     * Sets the value of the paritairComite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParitairComite(String value) {
        this.paritairComite = value;
    }

    /**
     * Gets the value of the employeeStatute property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeStatuteType }
     *     
     */
    public EmployeeStatuteType getEmployeeStatute() {
        return employeeStatute;
    }

    /**
     * Sets the value of the employeeStatute property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeStatuteType }
     *     
     */
    public void setEmployeeStatute(EmployeeStatuteType value) {
        this.employeeStatute = value;
    }

}
