//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 11:26:09 AM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v1.contractevent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContractType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContractType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="flexiDay" type="{http://www.securex.be/contractevent/v1}FlexiDayType"/&gt;
 *         &lt;element name="flexiPeriod" type="{http://www.securex.be/contractevent/v1}FlexiPeriodType"/&gt;
 *         &lt;element name="xtra" type="{http://www.securex.be/contractevent/v1}XtraType"/&gt;
 *         &lt;element name="student" type="{http://www.securex.be/contractevent/v1}StudentType"/&gt;
 *         &lt;element name="definiteTerm" type="{http://www.securex.be/contractevent/v1}DefiniteTermType"/&gt;
 *         &lt;element name="indefiniteTerm" type="{http://www.securex.be/contractevent/v1}IndefiniteTermType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractType", propOrder = {
    "flexiDay",
    "flexiPeriod",
    "xtra",
    "student",
    "definiteTerm",
    "indefiniteTerm"
})
public class ContractType {

    protected FlexiDayType flexiDay;
    protected FlexiPeriodType flexiPeriod;
    protected XtraType xtra;
    protected StudentType student;
    protected DefiniteTermType definiteTerm;
    protected IndefiniteTermType indefiniteTerm;

    /**
     * Gets the value of the flexiDay property.
     * 
     * @return
     *     possible object is
     *     {@link FlexiDayType }
     *     
     */
    public FlexiDayType getFlexiDay() {
        return flexiDay;
    }

    /**
     * Sets the value of the flexiDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlexiDayType }
     *     
     */
    public void setFlexiDay(FlexiDayType value) {
        this.flexiDay = value;
    }

    /**
     * Gets the value of the flexiPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link FlexiPeriodType }
     *     
     */
    public FlexiPeriodType getFlexiPeriod() {
        return flexiPeriod;
    }

    /**
     * Sets the value of the flexiPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlexiPeriodType }
     *     
     */
    public void setFlexiPeriod(FlexiPeriodType value) {
        this.flexiPeriod = value;
    }

    /**
     * Gets the value of the xtra property.
     * 
     * @return
     *     possible object is
     *     {@link XtraType }
     *     
     */
    public XtraType getXtra() {
        return xtra;
    }

    /**
     * Sets the value of the xtra property.
     * 
     * @param value
     *     allowed object is
     *     {@link XtraType }
     *     
     */
    public void setXtra(XtraType value) {
        this.xtra = value;
    }

    /**
     * Gets the value of the student property.
     * 
     * @return
     *     possible object is
     *     {@link StudentType }
     *     
     */
    public StudentType getStudent() {
        return student;
    }

    /**
     * Sets the value of the student property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentType }
     *     
     */
    public void setStudent(StudentType value) {
        this.student = value;
    }

    /**
     * Gets the value of the definiteTerm property.
     * 
     * @return
     *     possible object is
     *     {@link DefiniteTermType }
     *     
     */
    public DefiniteTermType getDefiniteTerm() {
        return definiteTerm;
    }

    /**
     * Sets the value of the definiteTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefiniteTermType }
     *     
     */
    public void setDefiniteTerm(DefiniteTermType value) {
        this.definiteTerm = value;
    }

    /**
     * Gets the value of the indefiniteTerm property.
     * 
     * @return
     *     possible object is
     *     {@link IndefiniteTermType }
     *     
     */
    public IndefiniteTermType getIndefiniteTerm() {
        return indefiniteTerm;
    }

    /**
     * Sets the value of the indefiniteTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndefiniteTermType }
     *     
     */
    public void setIndefiniteTerm(IndefiniteTermType value) {
        this.indefiniteTerm = value;
    }

}
