//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 11:26:09 AM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v1.contractevent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="metaData" type="{http://www.securex.be/contractevent/v1}MetaDataType"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="newContract"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;extension base="{http://www.securex.be/contractevent/v1}NewContractType"&gt;
 *                 &lt;/extension&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="updateContract" type="{http://www.securex.be/contractevent/v1}UpdateContractType"/&gt;
 *           &lt;element name="cancelContract" type="{http://www.securex.be/contractevent/v1}CancelContractType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metaData",
    "newContract",
    "updateContract",
    "cancelContract"
})
@XmlRootElement(name = "ContractEvent")
public class ContractEvent {

    @XmlElement(required = true)
    protected MetaDataType metaData;
    protected ContractEvent.NewContract newContract;
    protected UpdateContractType updateContract;
    protected CancelContractType cancelContract;

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDataType }
     *     
     */
    public MetaDataType getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDataType }
     *     
     */
    public void setMetaData(MetaDataType value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the newContract property.
     * 
     * @return
     *     possible object is
     *     {@link ContractEvent.NewContract }
     *     
     */
    public ContractEvent.NewContract getNewContract() {
        return newContract;
    }

    /**
     * Sets the value of the newContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractEvent.NewContract }
     *     
     */
    public void setNewContract(ContractEvent.NewContract value) {
        this.newContract = value;
    }

    /**
     * Gets the value of the updateContract property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateContractType }
     *     
     */
    public UpdateContractType getUpdateContract() {
        return updateContract;
    }

    /**
     * Sets the value of the updateContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateContractType }
     *     
     */
    public void setUpdateContract(UpdateContractType value) {
        this.updateContract = value;
    }

    /**
     * Gets the value of the cancelContract property.
     * 
     * @return
     *     possible object is
     *     {@link CancelContractType }
     *     
     */
    public CancelContractType getCancelContract() {
        return cancelContract;
    }

    /**
     * Sets the value of the cancelContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancelContractType }
     *     
     */
    public void setCancelContract(CancelContractType value) {
        this.cancelContract = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.securex.be/contractevent/v1}NewContractType"&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NewContract
        extends NewContractType
    {


    }

}
