//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 11:26:09 AM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v1.contractevent;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmployeeStatuteType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EmployeeStatuteType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="worker"/&gt;
 *     &lt;enumeration value="employee"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EmployeeStatuteType")
@XmlEnum
public enum EmployeeStatuteType {

    @XmlEnumValue("worker")
    WORKER("worker"),
    @XmlEnumValue("employee")
    EMPLOYEE("employee");
    private final String value;

    EmployeeStatuteType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EmployeeStatuteType fromValue(String v) {
        for (EmployeeStatuteType c: EmployeeStatuteType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
