//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 12:28:12 PM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v1.contractevent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModificationEmployeeInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModificationEmployeeInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.securex.be/contractevent/v1}EmployeeInfoType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="address" type="{http://www.securex.be/contractevent/v1}ModificationAddressType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModificationEmployeeInfoType", propOrder = {
    "address"
})
public class ModificationEmployeeInfoType
    extends EmployeeInfoType
{

    protected ModificationAddressType address;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link ModificationAddressType }
     *     
     */
    public ModificationAddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModificationAddressType }
     *     
     */
    public void setAddress(ModificationAddressType value) {
        this.address = value;
    }

}
