//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 12:28:12 PM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v1.contractevent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import java.util.UUID;


/**
 * <p>Java class for NewContractType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NewContractType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="employeeInfo" type="{http://www.securex.be/contractevent/v1}EmployeeInfoType"/&gt;
 *         &lt;element name="contractInfo" type="{http://www.securex.be/contractevent/v1}ContractInfoType"/&gt;
 *         &lt;element name="contractUuid" type="{http://www.securex.be/contractevent/v1}ContractUuidType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NewContractType", propOrder = {
    "employeeInfo",
    "contractInfo",
    "contractUuid"
})
@XmlSeeAlso({
    be.securex.sss.dimonaconverterservice.xsd.v1.contractevent.ContractEvent.NewContract.class
})
public class NewContractType {

    @XmlElement(required = true)
    protected CreationEmployeeInfoType employeeInfo;
    @XmlElement(required = true)
    protected ContractInfoType contractInfo;
    @XmlElement(required = true)
    protected UUID contractUuid;

    /**
     * Gets the value of the employeeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CreationEmployeeInfoType }
     *     
     */
    public CreationEmployeeInfoType getEmployeeInfo() {
        return employeeInfo;
    }

    /**
     * Sets the value of the employeeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationEmployeeInfoType }
     *     
     */
    public void setEmployeeInfo(CreationEmployeeInfoType value) {
        this.employeeInfo = value;
    }

    /**
     * Gets the value of the contractInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContractInfoType }
     *     
     */
    public ContractInfoType getContractInfo() {
        return contractInfo;
    }

    /**
     * Sets the value of the contractInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractInfoType }
     *     
     */
    public void setContractInfo(ContractInfoType value) {
        this.contractInfo = value;
    }

    /**
     * Gets the value of the contractUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public UUID getContractUuid() {
        return contractUuid;
    }

    /**
     * Sets the value of the contractUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractUuid(UUID value) {
        this.contractUuid = value;
    }

}
