//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 12:28:12 PM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v1.contractevent;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.securex.sss.dimonaconverterservice.xsd.v1.contractevent package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ContractIdentifierTypeContractId_QNAME = new QName("http://www.securex.be/contractevent/v1", "contractId");
    private final static QName _ContractIdentifierTypeContractUuid_QNAME = new QName("http://www.securex.be/contractevent/v1", "contractUuid");
    private final static QName _ContractIdentifierTypeSapPerNr_QNAME = new QName("http://www.securex.be/contractevent/v1", "sapPerNr");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.securex.sss.dimonaconverterservice.xsd.v1.contractevent
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContractEvent }
     * 
     */
    public ContractEvent createContractEvent() {
        return new ContractEvent();
    }

    /**
     * Create an instance of {@link MetaDataType }
     * 
     */
    public MetaDataType createMetaDataType() {
        return new MetaDataType();
    }

    /**
     * Create an instance of {@link ContractEvent.NewContract }
     * 
     */
    public ContractEvent.NewContract createContractEventNewContract() {
        return new ContractEvent.NewContract();
    }

    /**
     * Create an instance of {@link UpdateContractType }
     * 
     */
    public UpdateContractType createUpdateContractType() {
        return new UpdateContractType();
    }

    /**
     * Create an instance of {@link CancelContractType }
     * 
     */
    public CancelContractType createCancelContractType() {
        return new CancelContractType();
    }

    /**
     * Create an instance of {@link CreationAddressType }
     * 
     */
    public CreationAddressType createCreationAddressType() {
        return new CreationAddressType();
    }

    /**
     * Create an instance of {@link ModificationAddressType }
     * 
     */
    public ModificationAddressType createModificationAddressType() {
        return new ModificationAddressType();
    }

    /**
     * Create an instance of {@link CreationEmployeeInfoType }
     * 
     */
    public CreationEmployeeInfoType createCreationEmployeeInfoType() {
        return new CreationEmployeeInfoType();
    }

    /**
     * Create an instance of {@link ModificationEmployeeInfoType }
     * 
     */
    public ModificationEmployeeInfoType createModificationEmployeeInfoType() {
        return new ModificationEmployeeInfoType();
    }

    /**
     * Create an instance of {@link ContractInfoType }
     * 
     */
    public ContractInfoType createContractInfoType() {
        return new ContractInfoType();
    }

    /**
     * Create an instance of {@link ContractIdentifierType }
     * 
     */
    public ContractIdentifierType createContractIdentifierType() {
        return new ContractIdentifierType();
    }

    /**
     * Create an instance of {@link XtraType }
     * 
     */
    public XtraType createXtraType() {
        return new XtraType();
    }

    /**
     * Create an instance of {@link WorkHoursType }
     * 
     */
    public WorkHoursType createWorkHoursType() {
        return new WorkHoursType();
    }

    /**
     * Create an instance of {@link FlexiDayType }
     * 
     */
    public FlexiDayType createFlexiDayType() {
        return new FlexiDayType();
    }

    /**
     * Create an instance of {@link FlexiPeriodType }
     * 
     */
    public FlexiPeriodType createFlexiPeriodType() {
        return new FlexiPeriodType();
    }

    /**
     * Create an instance of {@link StudentType }
     * 
     */
    public StudentType createStudentType() {
        return new StudentType();
    }

    /**
     * Create an instance of {@link DefiniteTermType }
     * 
     */
    public DefiniteTermType createDefiniteTermType() {
        return new DefiniteTermType();
    }

    /**
     * Create an instance of {@link IndefiniteTermType }
     * 
     */
    public IndefiniteTermType createIndefiniteTermType() {
        return new IndefiniteTermType();
    }

    /**
     * Create an instance of {@link FDCPType }
     * 
     */
    public FDCPType createFDCPType() {
        return new FDCPType();
    }

    /**
     * Create an instance of {@link ContractType }
     * 
     */
    public ContractType createContractType() {
        return new ContractType();
    }

    /**
     * Create an instance of {@link ContractEventType }
     * 
     */
    public ContractEventType createContractEventType() {
        return new ContractEventType();
    }

    /**
     * Create an instance of {@link NewContractType }
     * 
     */
    public NewContractType createNewContractType() {
        return new NewContractType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.securex.be/contractevent/v1", name = "contractId", scope = ContractIdentifierType.class)
    public JAXBElement<String> createContractIdentifierTypeContractId(String value) {
        return new JAXBElement<String>(_ContractIdentifierTypeContractId_QNAME, String.class, ContractIdentifierType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.securex.be/contractevent/v1", name = "contractUuid", scope = ContractIdentifierType.class)
    public JAXBElement<String> createContractIdentifierTypeContractUuid(String value) {
        return new JAXBElement<String>(_ContractIdentifierTypeContractUuid_QNAME, String.class, ContractIdentifierType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.securex.be/contractevent/v1", name = "sapPerNr", scope = ContractIdentifierType.class)
    public JAXBElement<String> createContractIdentifierTypeSapPerNr(String value) {
        return new JAXBElement<String>(_ContractIdentifierTypeSapPerNr_QNAME, String.class, ContractIdentifierType.class, value);
    }

}
