//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 12:28:12 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.securex.be/contractevent/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.securex.sss.dimonaconverterservice.xsd.v1.contractevent;
