//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 10:59:09 AM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v4.hronline;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dimona change student
 * 
 * <p>Java class for ChangeStudentCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeStudentCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IT9753" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="EmploymentAddressRefNumber" type="{}StringPatternRefNumber"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="GIT0016" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Planneddaysnbr" type="{}StringPatternNumber99"/&gt;
 *                   &lt;element name="Plannedhoursnbr" type="{}StringPatternNumber999"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeStudentCType", propOrder = {
    "it9753",
    "git0016"
})
public class ChangeStudentCType {

    @XmlElement(name = "IT9753")
    protected ChangeStudentCType.IT9753 it9753;
    @XmlElement(name = "GIT0016")
    protected ChangeStudentCType.GIT0016 git0016;

    /**
     * Gets the value of the it9753 property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeStudentCType.IT9753 }
     *     
     */
    public ChangeStudentCType.IT9753 getIT9753() {
        return it9753;
    }

    /**
     * Sets the value of the it9753 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeStudentCType.IT9753 }
     *     
     */
    public void setIT9753(ChangeStudentCType.IT9753 value) {
        this.it9753 = value;
    }

    /**
     * Gets the value of the git0016 property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeStudentCType.GIT0016 }
     *     
     */
    public ChangeStudentCType.GIT0016 getGIT0016() {
        return git0016;
    }

    /**
     * Sets the value of the git0016 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeStudentCType.GIT0016 }
     *     
     */
    public void setGIT0016(ChangeStudentCType.GIT0016 value) {
        this.git0016 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Planneddaysnbr" type="{}StringPatternNumber99"/&gt;
     *         &lt;element name="Plannedhoursnbr" type="{}StringPatternNumber999"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "planneddaysnbr",
        "plannedhoursnbr"
    })
    public static class GIT0016 {

        @XmlElement(name = "Planneddaysnbr")
        protected String planneddaysnbr;
        @XmlElement(name = "Plannedhoursnbr")
        protected String plannedhoursnbr;

        /**
         * Gets the value of the planneddaysnbr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanneddaysnbr() {
            return planneddaysnbr;
        }

        /**
         * Sets the value of the planneddaysnbr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanneddaysnbr(String value) {
            this.planneddaysnbr = value;
        }

        /**
         * Gets the value of the plannedhoursnbr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlannedhoursnbr() {
            return plannedhoursnbr;
        }

        /**
         * Sets the value of the plannedhoursnbr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlannedhoursnbr(String value) {
            this.plannedhoursnbr = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="EmploymentAddressRefNumber" type="{}StringPatternRefNumber"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "employmentAddressRefNumber"
    })
    public static class IT9753 {

        @XmlElement(name = "EmploymentAddressRefNumber", required = true)
        protected String employmentAddressRefNumber;

        /**
         * Gets the value of the employmentAddressRefNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmploymentAddressRefNumber() {
            return employmentAddressRefNumber;
        }

        /**
         * Sets the value of the employmentAddressRefNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmploymentAddressRefNumber(String value) {
            this.employmentAddressRefNumber = value;
        }

    }

}
