//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 10:59:09 AM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v4.hronline;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * only for occasional worker/Flexi 1 day/extra
 * 
 * <p>Java class for ChangeExtraFlexiCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeExtraFlexiCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IT2003" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="validFrom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="validTo" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
 *                   &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
 *                   &lt;element name="break" type="{}StringPatternAmount4_2_No_Sign" minOccurs="0"/&gt;
 *                   &lt;element name="endTimeOnNextDay" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeExtraFlexiCType", propOrder = {
    "it2003"
})
public class ChangeExtraFlexiCType {

    @XmlElement(name = "IT2003")
    protected List<ChangeExtraFlexiCType.IT2003> it2003;

    /**
     * Gets the value of the it2003 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the it2003 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIT2003().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChangeExtraFlexiCType.IT2003 }
     * 
     * 
     */
    public List<ChangeExtraFlexiCType.IT2003> getIT2003() {
        if (it2003 == null) {
            it2003 = new ArrayList<ChangeExtraFlexiCType.IT2003>();
        }
        return this.it2003;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="validFrom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="validTo" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
     *         &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
     *         &lt;element name="break" type="{}StringPatternAmount4_2_No_Sign" minOccurs="0"/&gt;
     *         &lt;element name="endTimeOnNextDay" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "validFrom",
        "validTo",
        "startTime",
        "endTime",
        "_break",
        "endTimeOnNextDay"
    })
    public static class IT2003 {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar validFrom;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar validTo;
        @XmlElement(required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar startTime;
        @XmlElement(required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar endTime;
        @XmlElement(name = "break")
        protected String _break;
        protected boolean endTimeOnNextDay;

        /**
         * Gets the value of the validFrom property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValidFrom() {
            return validFrom;
        }

        /**
         * Sets the value of the validFrom property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValidFrom(XMLGregorianCalendar value) {
            this.validFrom = value;
        }

        /**
         * Gets the value of the validTo property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValidTo() {
            return validTo;
        }

        /**
         * Sets the value of the validTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValidTo(XMLGregorianCalendar value) {
            this.validTo = value;
        }

        /**
         * Gets the value of the startTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartTime() {
            return startTime;
        }

        /**
         * Sets the value of the startTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartTime(XMLGregorianCalendar value) {
            this.startTime = value;
        }

        /**
         * Gets the value of the endTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndTime() {
            return endTime;
        }

        /**
         * Sets the value of the endTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndTime(XMLGregorianCalendar value) {
            this.endTime = value;
        }

        /**
         * Gets the value of the break property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBreak() {
            return _break;
        }

        /**
         * Sets the value of the break property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBreak(String value) {
            this._break = value;
        }

        /**
         * Gets the value of the endTimeOnNextDay property.
         * 
         */
        public boolean isEndTimeOnNextDay() {
            return endTimeOnNextDay;
        }

        /**
         * Sets the value of the endTimeOnNextDay property.
         * 
         */
        public void setEndTimeOnNextDay(boolean value) {
            this.endTimeOnNextDay = value;
        }

    }

}
