//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 10:59:09 AM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v4.hronline;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * Mini hire
 * 
 * <p>Java class for HireCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HireCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IT0000"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ContractStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="ContractEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IT0001"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="EmployeeGroup" type="{}StringPattern1Char"/&gt;
 *                   &lt;element name="EmployeeSubgroup" type="{}StringPattern2Chars"/&gt;
 *                   &lt;element name="WorkContract" type="{}StringPattern2Chars"/&gt;
 *                   &lt;element name="Departement" type="{}StringPattern4Chars" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IT0002"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Title" type="{}StringPattern1Char"/&gt;
 *                   &lt;element name="FirstName"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value=".{0,30}"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="LastName"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value=".{0,40}"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Initials" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value="([A-Z]|[a-z])?"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Gender"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value="1|2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="BirthPlace" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value=".{0,50}"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="CountryOfBirth" type="{}SecurexCountryCode" minOccurs="0"/&gt;
 *                   &lt;element name="Nationality" type="{}SecurexCountryCode"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IT0100" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INSSNumber" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value="([0-9]{11})?"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IT0016"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ContractType" type="{}StringPattern2Chars"/&gt;
 *                   &lt;element name="LabourCommission"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value=".{0,3}"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IT0109" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="C32ACardNbrCurrentMonth"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value="([0-9]{12})?"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="C32ACardNbrNextMonth"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value="([0-9]{12})?"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IT0006" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Street" type="{}StringPattern40Chars"/&gt;
 *                   &lt;element name="HouseNumber" type="{}StringPattern10Chars"/&gt;
 *                   &lt;element name="MailBoxNumber" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value=".{0,10}"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="SecondAddressLine" type="{}StringPattern40Chars" minOccurs="0"/&gt;
 *                   &lt;element name="PostalCode" type="{}StringPattern10Chars"/&gt;
 *                   &lt;element name="City" type="{}StringPattern40Chars" minOccurs="0"/&gt;
 *                   &lt;element name="Country" type="{}SecurexCountryCode"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IT2003" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="validFrom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="validTo" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
 *                   &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
 *                   &lt;element name="break" type="{}StringPatternAmount4_2_No_Sign" minOccurs="0"/&gt;
 *                   &lt;element name="endTimeOnNextDay" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IT0007" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CONTINGENT" type="{}StringPattern2Chars"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IT9753" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="EmploymentAddressRefNumber" type="{}StringPatternRefNumber"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="GIT0016" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Planneddaysnbr" type="{}StringPatternNumber99"/&gt;
 *                   &lt;element name="Plannedhoursnbr" type="{}StringPatternNumber999"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HireCType", propOrder = {
    "it0000",
    "it0001",
    "it0002",
    "it0100",
    "it0016",
    "it0109",
    "it0006",
    "it2003",
    "it0007",
    "it9753",
    "git0016"
})
public class HireCType {

    @XmlElement(name = "IT0000", required = true)
    protected HireCType.IT0000 it0000;
    @XmlElement(name = "IT0001", required = true)
    protected HireCType.IT0001 it0001;
    @XmlElement(name = "IT0002", required = true)
    protected HireCType.IT0002 it0002;
    @XmlElement(name = "IT0100")
    protected HireCType.IT0100 it0100;
    @XmlElement(name = "IT0016", required = true)
    protected HireCType.IT0016 it0016;
    @XmlElement(name = "IT0109")
    protected HireCType.IT0109 it0109;
    @XmlElement(name = "IT0006")
    protected HireCType.IT0006 it0006;
    @XmlElement(name = "IT2003")
    protected List<HireCType.IT2003> it2003;
    @XmlElement(name = "IT0007")
    protected HireCType.IT0007 it0007;
    @XmlElement(name = "IT9753")
    protected HireCType.IT9753 it9753;
    @XmlElement(name = "GIT0016")
    protected HireCType.GIT0016 git0016;

    /**
     * Gets the value of the it0000 property.
     * 
     * @return
     *     possible object is
     *     {@link HireCType.IT0000 }
     *     
     */
    public HireCType.IT0000 getIT0000() {
        return it0000;
    }

    /**
     * Sets the value of the it0000 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HireCType.IT0000 }
     *     
     */
    public void setIT0000(HireCType.IT0000 value) {
        this.it0000 = value;
    }

    /**
     * Gets the value of the it0001 property.
     * 
     * @return
     *     possible object is
     *     {@link HireCType.IT0001 }
     *     
     */
    public HireCType.IT0001 getIT0001() {
        return it0001;
    }

    /**
     * Sets the value of the it0001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HireCType.IT0001 }
     *     
     */
    public void setIT0001(HireCType.IT0001 value) {
        this.it0001 = value;
    }

    /**
     * Gets the value of the it0002 property.
     * 
     * @return
     *     possible object is
     *     {@link HireCType.IT0002 }
     *     
     */
    public HireCType.IT0002 getIT0002() {
        return it0002;
    }

    /**
     * Sets the value of the it0002 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HireCType.IT0002 }
     *     
     */
    public void setIT0002(HireCType.IT0002 value) {
        this.it0002 = value;
    }

    /**
     * Gets the value of the it0100 property.
     * 
     * @return
     *     possible object is
     *     {@link HireCType.IT0100 }
     *     
     */
    public HireCType.IT0100 getIT0100() {
        return it0100;
    }

    /**
     * Sets the value of the it0100 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HireCType.IT0100 }
     *     
     */
    public void setIT0100(HireCType.IT0100 value) {
        this.it0100 = value;
    }

    /**
     * Gets the value of the it0016 property.
     * 
     * @return
     *     possible object is
     *     {@link HireCType.IT0016 }
     *     
     */
    public HireCType.IT0016 getIT0016() {
        return it0016;
    }

    /**
     * Sets the value of the it0016 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HireCType.IT0016 }
     *     
     */
    public void setIT0016(HireCType.IT0016 value) {
        this.it0016 = value;
    }

    /**
     * Gets the value of the it0109 property.
     * 
     * @return
     *     possible object is
     *     {@link HireCType.IT0109 }
     *     
     */
    public HireCType.IT0109 getIT0109() {
        return it0109;
    }

    /**
     * Sets the value of the it0109 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HireCType.IT0109 }
     *     
     */
    public void setIT0109(HireCType.IT0109 value) {
        this.it0109 = value;
    }

    /**
     * Gets the value of the it0006 property.
     * 
     * @return
     *     possible object is
     *     {@link HireCType.IT0006 }
     *     
     */
    public HireCType.IT0006 getIT0006() {
        return it0006;
    }

    /**
     * Sets the value of the it0006 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HireCType.IT0006 }
     *     
     */
    public void setIT0006(HireCType.IT0006 value) {
        this.it0006 = value;
    }

    /**
     * Gets the value of the it2003 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the it2003 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIT2003().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HireCType.IT2003 }
     * 
     * 
     */
    public List<HireCType.IT2003> getIT2003() {
        if (it2003 == null) {
            it2003 = new ArrayList<HireCType.IT2003>();
        }
        return this.it2003;
    }

    /**
     * Gets the value of the it0007 property.
     * 
     * @return
     *     possible object is
     *     {@link HireCType.IT0007 }
     *     
     */
    public HireCType.IT0007 getIT0007() {
        return it0007;
    }

    /**
     * Sets the value of the it0007 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HireCType.IT0007 }
     *     
     */
    public void setIT0007(HireCType.IT0007 value) {
        this.it0007 = value;
    }

    /**
     * Gets the value of the it9753 property.
     * 
     * @return
     *     possible object is
     *     {@link HireCType.IT9753 }
     *     
     */
    public HireCType.IT9753 getIT9753() {
        return it9753;
    }

    /**
     * Sets the value of the it9753 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HireCType.IT9753 }
     *     
     */
    public void setIT9753(HireCType.IT9753 value) {
        this.it9753 = value;
    }

    /**
     * Gets the value of the git0016 property.
     * 
     * @return
     *     possible object is
     *     {@link HireCType.GIT0016 }
     *     
     */
    public HireCType.GIT0016 getGIT0016() {
        return git0016;
    }

    /**
     * Sets the value of the git0016 property.
     * 
     * @param value
     *     allowed object is
     *     {@link HireCType.GIT0016 }
     *     
     */
    public void setGIT0016(HireCType.GIT0016 value) {
        this.git0016 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Planneddaysnbr" type="{}StringPatternNumber99"/&gt;
     *         &lt;element name="Plannedhoursnbr" type="{}StringPatternNumber999"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "planneddaysnbr",
        "plannedhoursnbr"
    })
    public static class GIT0016 {

        @XmlElement(name = "Planneddaysnbr")
        protected String planneddaysnbr;
        @XmlElement(name = "Plannedhoursnbr")
        protected String plannedhoursnbr;

        /**
         * Gets the value of the planneddaysnbr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanneddaysnbr() {
            return planneddaysnbr;
        }

        /**
         * Sets the value of the planneddaysnbr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanneddaysnbr(String value) {
            this.planneddaysnbr = value;
        }

        /**
         * Gets the value of the plannedhoursnbr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlannedhoursnbr() {
            return plannedhoursnbr;
        }

        /**
         * Sets the value of the plannedhoursnbr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlannedhoursnbr(String value) {
            this.plannedhoursnbr = value;
        }

    }


    /**
     * Action data
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ContractStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="ContractEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contractStartDate",
        "contractEndDate"
    })
    public static class IT0000 {

        @XmlElement(name = "ContractStartDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar contractStartDate;
        @XmlElement(name = "ContractEndDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar contractEndDate;

        /**
         * Gets the value of the contractStartDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getContractStartDate() {
            return contractStartDate;
        }

        /**
         * Sets the value of the contractStartDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setContractStartDate(XMLGregorianCalendar value) {
            this.contractStartDate = value;
        }

        /**
         * Gets the value of the contractEndDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getContractEndDate() {
            return contractEndDate;
        }

        /**
         * Sets the value of the contractEndDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setContractEndDate(XMLGregorianCalendar value) {
            this.contractEndDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="EmployeeGroup" type="{}StringPattern1Char"/&gt;
     *         &lt;element name="EmployeeSubgroup" type="{}StringPattern2Chars"/&gt;
     *         &lt;element name="WorkContract" type="{}StringPattern2Chars"/&gt;
     *         &lt;element name="Departement" type="{}StringPattern4Chars" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "employeeGroup",
        "employeeSubgroup",
        "workContract",
        "departement"
    })
    public static class IT0001 {

        @XmlElement(name = "EmployeeGroup", required = true)
        protected String employeeGroup;
        @XmlElement(name = "EmployeeSubgroup", required = true)
        protected String employeeSubgroup;
        @XmlElement(name = "WorkContract", required = true)
        protected String workContract;
        @XmlElement(name = "Departement")
        protected String departement;

        /**
         * Gets the value of the employeeGroup property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmployeeGroup() {
            return employeeGroup;
        }

        /**
         * Sets the value of the employeeGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmployeeGroup(String value) {
            this.employeeGroup = value;
        }

        /**
         * Gets the value of the employeeSubgroup property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmployeeSubgroup() {
            return employeeSubgroup;
        }

        /**
         * Sets the value of the employeeSubgroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmployeeSubgroup(String value) {
            this.employeeSubgroup = value;
        }

        /**
         * Gets the value of the workContract property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkContract() {
            return workContract;
        }

        /**
         * Sets the value of the workContract property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkContract(String value) {
            this.workContract = value;
        }

        /**
         * Gets the value of the departement property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepartement() {
            return departement;
        }

        /**
         * Sets the value of the departement property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepartement(String value) {
            this.departement = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Title" type="{}StringPattern1Char"/&gt;
     *         &lt;element name="FirstName"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value=".{0,30}"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="LastName"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value=".{0,40}"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Initials" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value="([A-Z]|[a-z])?"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Gender"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value="1|2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="BirthPlace" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value=".{0,50}"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="CountryOfBirth" type="{}SecurexCountryCode" minOccurs="0"/&gt;
     *         &lt;element name="Nationality" type="{}SecurexCountryCode"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "firstName",
        "lastName",
        "initials",
        "gender",
        "birthDate",
        "birthPlace",
        "countryOfBirth",
        "nationality"
    })
    public static class IT0002 {

        @XmlElement(name = "Title", required = true)
        protected String title;
        @XmlElement(name = "FirstName", required = true)
        protected String firstName;
        @XmlElement(name = "LastName", required = true)
        protected String lastName;
        @XmlElement(name = "Initials")
        protected String initials;
        @XmlElement(name = "Gender", required = true)
        protected String gender;
        @XmlElement(name = "BirthDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar birthDate;
        @XmlElement(name = "BirthPlace")
        protected String birthPlace;
        @XmlElement(name = "CountryOfBirth")
        protected String countryOfBirth;
        @XmlElement(name = "Nationality", required = true)
        protected String nationality;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the initials property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInitials() {
            return initials;
        }

        /**
         * Sets the value of the initials property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInitials(String value) {
            this.initials = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGender(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the birthDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getBirthDate() {
            return birthDate;
        }

        /**
         * Sets the value of the birthDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setBirthDate(XMLGregorianCalendar value) {
            this.birthDate = value;
        }

        /**
         * Gets the value of the birthPlace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBirthPlace() {
            return birthPlace;
        }

        /**
         * Sets the value of the birthPlace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBirthPlace(String value) {
            this.birthPlace = value;
        }

        /**
         * Gets the value of the countryOfBirth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryOfBirth() {
            return countryOfBirth;
        }

        /**
         * Sets the value of the countryOfBirth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryOfBirth(String value) {
            this.countryOfBirth = value;
        }

        /**
         * Gets the value of the nationality property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNationality() {
            return nationality;
        }

        /**
         * Sets the value of the nationality property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNationality(String value) {
            this.nationality = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Street" type="{}StringPattern40Chars"/&gt;
     *         &lt;element name="HouseNumber" type="{}StringPattern10Chars"/&gt;
     *         &lt;element name="MailBoxNumber" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value=".{0,10}"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="SecondAddressLine" type="{}StringPattern40Chars" minOccurs="0"/&gt;
     *         &lt;element name="PostalCode" type="{}StringPattern10Chars"/&gt;
     *         &lt;element name="City" type="{}StringPattern40Chars" minOccurs="0"/&gt;
     *         &lt;element name="Country" type="{}SecurexCountryCode"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "street",
        "houseNumber",
        "mailBoxNumber",
        "secondAddressLine",
        "postalCode",
        "city",
        "country"
    })
    public static class IT0006 {

        @XmlElement(name = "Street", required = true)
        protected String street;
        @XmlElement(name = "HouseNumber", required = true)
        protected String houseNumber;
        @XmlElement(name = "MailBoxNumber")
        protected String mailBoxNumber;
        @XmlElement(name = "SecondAddressLine")
        protected String secondAddressLine;
        @XmlElement(name = "PostalCode", required = true)
        protected String postalCode;
        @XmlElement(name = "City")
        protected String city;
        @XmlElement(name = "Country", required = true)
        protected String country;

        /**
         * Gets the value of the street property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStreet() {
            return street;
        }

        /**
         * Sets the value of the street property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStreet(String value) {
            this.street = value;
        }

        /**
         * Gets the value of the houseNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHouseNumber() {
            return houseNumber;
        }

        /**
         * Sets the value of the houseNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHouseNumber(String value) {
            this.houseNumber = value;
        }

        /**
         * Gets the value of the mailBoxNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMailBoxNumber() {
            return mailBoxNumber;
        }

        /**
         * Sets the value of the mailBoxNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMailBoxNumber(String value) {
            this.mailBoxNumber = value;
        }

        /**
         * Gets the value of the secondAddressLine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSecondAddressLine() {
            return secondAddressLine;
        }

        /**
         * Sets the value of the secondAddressLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSecondAddressLine(String value) {
            this.secondAddressLine = value;
        }

        /**
         * Gets the value of the postalCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPostalCode() {
            return postalCode;
        }

        /**
         * Sets the value of the postalCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPostalCode(String value) {
            this.postalCode = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CONTINGENT" type="{}StringPattern2Chars"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contingent"
    })
    public static class IT0007 {

        @XmlElement(name = "CONTINGENT", required = true)
        protected String contingent;

        /**
         * Gets the value of the contingent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCONTINGENT() {
            return contingent;
        }

        /**
         * Sets the value of the contingent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCONTINGENT(String value) {
            this.contingent = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ContractType" type="{}StringPattern2Chars"/&gt;
     *         &lt;element name="LabourCommission"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value=".{0,3}"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contractType",
        "labourCommission"
    })
    public static class IT0016 {

        @XmlElement(name = "ContractType", required = true)
        protected String contractType;
        @XmlElement(name = "LabourCommission", required = true)
        protected String labourCommission;

        /**
         * Gets the value of the contractType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractType() {
            return contractType;
        }

        /**
         * Sets the value of the contractType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractType(String value) {
            this.contractType = value;
        }

        /**
         * Gets the value of the labourCommission property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabourCommission() {
            return labourCommission;
        }

        /**
         * Sets the value of the labourCommission property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabourCommission(String value) {
            this.labourCommission = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INSSNumber" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value="([0-9]{11})?"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "inssNumber"
    })
    public static class IT0100 {

        @XmlElement(name = "INSSNumber")
        protected String inssNumber;

        /**
         * Gets the value of the inssNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINSSNumber() {
            return inssNumber;
        }

        /**
         * Sets the value of the inssNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINSSNumber(String value) {
            this.inssNumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="C32ACardNbrCurrentMonth"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value="([0-9]{12})?"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="C32ACardNbrNextMonth"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value="([0-9]{12})?"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "c32ACardNbrCurrentMonth",
        "c32ACardNbrNextMonth"
    })
    public static class IT0109 {

        @XmlElement(name = "C32ACardNbrCurrentMonth", required = true)
        protected String c32ACardNbrCurrentMonth;
        @XmlElement(name = "C32ACardNbrNextMonth", required = true)
        protected String c32ACardNbrNextMonth;

        /**
         * Gets the value of the c32ACardNbrCurrentMonth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getC32ACardNbrCurrentMonth() {
            return c32ACardNbrCurrentMonth;
        }

        /**
         * Sets the value of the c32ACardNbrCurrentMonth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setC32ACardNbrCurrentMonth(String value) {
            this.c32ACardNbrCurrentMonth = value;
        }

        /**
         * Gets the value of the c32ACardNbrNextMonth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getC32ACardNbrNextMonth() {
            return c32ACardNbrNextMonth;
        }

        /**
         * Sets the value of the c32ACardNbrNextMonth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setC32ACardNbrNextMonth(String value) {
            this.c32ACardNbrNextMonth = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="validFrom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="validTo" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
     *         &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
     *         &lt;element name="break" type="{}StringPatternAmount4_2_No_Sign" minOccurs="0"/&gt;
     *         &lt;element name="endTimeOnNextDay" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "validFrom",
        "validTo",
        "startTime",
        "endTime",
        "_break",
        "endTimeOnNextDay"
    })
    public static class IT2003 {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar validFrom;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar validTo;
        @XmlElement(required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar startTime;
        @XmlElement(required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar endTime;
        @XmlElement(name = "break")
        protected String _break;
        protected boolean endTimeOnNextDay;

        /**
         * Gets the value of the validFrom property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValidFrom() {
            return validFrom;
        }

        /**
         * Sets the value of the validFrom property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValidFrom(XMLGregorianCalendar value) {
            this.validFrom = value;
        }

        /**
         * Gets the value of the validTo property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValidTo() {
            return validTo;
        }

        /**
         * Sets the value of the validTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValidTo(XMLGregorianCalendar value) {
            this.validTo = value;
        }

        /**
         * Gets the value of the startTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartTime() {
            return startTime;
        }

        /**
         * Sets the value of the startTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartTime(XMLGregorianCalendar value) {
            this.startTime = value;
        }

        /**
         * Gets the value of the endTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndTime() {
            return endTime;
        }

        /**
         * Sets the value of the endTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndTime(XMLGregorianCalendar value) {
            this.endTime = value;
        }

        /**
         * Gets the value of the break property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBreak() {
            return _break;
        }

        /**
         * Sets the value of the break property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBreak(String value) {
            this._break = value;
        }

        /**
         * Gets the value of the endTimeOnNextDay property.
         * 
         */
        public boolean isEndTimeOnNextDay() {
            return endTimeOnNextDay;
        }

        /**
         * Sets the value of the endTimeOnNextDay property.
         * 
         */
        public void setEndTimeOnNextDay(boolean value) {
            this.endTimeOnNextDay = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="EmploymentAddressRefNumber" type="{}StringPatternRefNumber"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "employmentAddressRefNumber"
    })
    public static class IT9753 {

        @XmlElement(name = "EmploymentAddressRefNumber", required = true)
        protected String employmentAddressRefNumber;

        /**
         * Gets the value of the employmentAddressRefNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmploymentAddressRefNumber() {
            return employmentAddressRefNumber;
        }

        /**
         * Sets the value of the employmentAddressRefNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmploymentAddressRefNumber(String value) {
            this.employmentAddressRefNumber = value;
        }

    }

}
