//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 10:59:09 AM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v4.hronline;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.securex.sss.dimonaconverterservice.xsd.v4.hronline package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.securex.sss.dimonaconverterservice.xsd.v4.hronline
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChangeExtraFlexiCType }
     * 
     */
    public ChangeExtraFlexiCType createChangeExtraFlexiCType() {
        return new ChangeExtraFlexiCType();
    }

    /**
     * Create an instance of {@link ChangeStudentCType }
     * 
     */
    public ChangeStudentCType createChangeStudentCType() {
        return new ChangeStudentCType();
    }

    /**
     * Create an instance of {@link TerminationCType }
     * 
     */
    public TerminationCType createTerminationCType() {
        return new TerminationCType();
    }

    /**
     * Create an instance of {@link HireCType }
     * 
     */
    public HireCType createHireCType() {
        return new HireCType();
    }

    /**
     * Create an instance of {@link KeyInfoCType }
     * 
     */
    public KeyInfoCType createKeyInfoCType() {
        return new KeyInfoCType();
    }

    /**
     * Create an instance of {@link KeyInfoCType.Id }
     * 
     */
    public KeyInfoCType.Id createKeyInfoCTypeId() {
        return new KeyInfoCType.Id();
    }

    /**
     * Create an instance of {@link Employee }
     * 
     */
    public Employee createEmployee() {
        return new Employee();
    }

    /**
     * Create an instance of {@link ScenarioInfoCType }
     * 
     */
    public ScenarioInfoCType createScenarioInfoCType() {
        return new ScenarioInfoCType();
    }

    /**
     * Create an instance of {@link AnnulationCType }
     * 
     */
    public AnnulationCType createAnnulationCType() {
        return new AnnulationCType();
    }

    /**
     * Create an instance of {@link ScenarioInfoContentCType }
     * 
     */
    public ScenarioInfoContentCType createScenarioInfoContentCType() {
        return new ScenarioInfoContentCType();
    }

    /**
     * Create an instance of {@link DeleteTerminationCType }
     * 
     */
    public DeleteTerminationCType createDeleteTerminationCType() {
        return new DeleteTerminationCType();
    }

    /**
     * Create an instance of {@link ChangeExtraFlexiCType.IT2003 }
     * 
     */
    public ChangeExtraFlexiCType.IT2003 createChangeExtraFlexiCTypeIT2003() {
        return new ChangeExtraFlexiCType.IT2003();
    }

    /**
     * Create an instance of {@link ChangeStudentCType.IT9753 }
     * 
     */
    public ChangeStudentCType.IT9753 createChangeStudentCTypeIT9753() {
        return new ChangeStudentCType.IT9753();
    }

    /**
     * Create an instance of {@link ChangeStudentCType.GIT0016 }
     * 
     */
    public ChangeStudentCType.GIT0016 createChangeStudentCTypeGIT0016() {
        return new ChangeStudentCType.GIT0016();
    }

    /**
     * Create an instance of {@link TerminationCType.IT0000 }
     * 
     */
    public TerminationCType.IT0000 createTerminationCTypeIT0000() {
        return new TerminationCType.IT0000();
    }

    /**
     * Create an instance of {@link HireCType.IT0000 }
     * 
     */
    public HireCType.IT0000 createHireCTypeIT0000() {
        return new HireCType.IT0000();
    }

    /**
     * Create an instance of {@link HireCType.IT0001 }
     * 
     */
    public HireCType.IT0001 createHireCTypeIT0001() {
        return new HireCType.IT0001();
    }

    /**
     * Create an instance of {@link HireCType.IT0002 }
     * 
     */
    public HireCType.IT0002 createHireCTypeIT0002() {
        return new HireCType.IT0002();
    }

    /**
     * Create an instance of {@link HireCType.IT0100 }
     * 
     */
    public HireCType.IT0100 createHireCTypeIT0100() {
        return new HireCType.IT0100();
    }

    /**
     * Create an instance of {@link HireCType.IT0016 }
     * 
     */
    public HireCType.IT0016 createHireCTypeIT0016() {
        return new HireCType.IT0016();
    }

    /**
     * Create an instance of {@link HireCType.IT0109 }
     * 
     */
    public HireCType.IT0109 createHireCTypeIT0109() {
        return new HireCType.IT0109();
    }

    /**
     * Create an instance of {@link HireCType.IT0006 }
     * 
     */
    public HireCType.IT0006 createHireCTypeIT0006() {
        return new HireCType.IT0006();
    }

    /**
     * Create an instance of {@link HireCType.IT2003 }
     * 
     */
    public HireCType.IT2003 createHireCTypeIT2003() {
        return new HireCType.IT2003();
    }

    /**
     * Create an instance of {@link HireCType.IT0007 }
     * 
     */
    public HireCType.IT0007 createHireCTypeIT0007() {
        return new HireCType.IT0007();
    }

    /**
     * Create an instance of {@link HireCType.IT9753 }
     * 
     */
    public HireCType.IT9753 createHireCTypeIT9753() {
        return new HireCType.IT9753();
    }

    /**
     * Create an instance of {@link HireCType.GIT0016 }
     * 
     */
    public HireCType.GIT0016 createHireCTypeGIT0016() {
        return new HireCType.GIT0016();
    }

    /**
     * Create an instance of {@link KeyInfoCType.Id.CompositeId }
     * 
     */
    public KeyInfoCType.Id.CompositeId createKeyInfoCTypeIdCompositeId() {
        return new KeyInfoCType.Id.CompositeId();
    }

}
