//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 10:59:09 AM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v4.hronline;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScenarioInfoContentCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScenarioInfoContentCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Hire" type="{}HireCType"/&gt;
 *         &lt;element name="Termination" type="{}TerminationCType"/&gt;
 *         &lt;element name="Annulation" type="{}AnnulationCType"/&gt;
 *         &lt;element name="DeleteTermination" type="{}DeleteTerminationCType"/&gt;
 *         &lt;element name="ChangeStudent" type="{}ChangeStudentCType"/&gt;
 *         &lt;element name="ChangeExtraFlexi" type="{}ChangeExtraFlexiCType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScenarioInfoContentCType", propOrder = {
    "hire",
    "termination",
    "annulation",
    "deleteTermination",
    "changeStudent",
    "changeExtraFlexi"
})
public class ScenarioInfoContentCType {

    @XmlElement(name = "Hire")
    protected HireCType hire;
    @XmlElement(name = "Termination")
    protected TerminationCType termination;
    @XmlElement(name = "Annulation")
    protected AnnulationCType annulation;
    @XmlElement(name = "DeleteTermination")
    protected DeleteTerminationCType deleteTermination;
    @XmlElement(name = "ChangeStudent")
    protected ChangeStudentCType changeStudent;
    @XmlElement(name = "ChangeExtraFlexi")
    protected ChangeExtraFlexiCType changeExtraFlexi;

    /**
     * Gets the value of the hire property.
     * 
     * @return
     *     possible object is
     *     {@link HireCType }
     *     
     */
    public HireCType getHire() {
        return hire;
    }

    /**
     * Sets the value of the hire property.
     * 
     * @param value
     *     allowed object is
     *     {@link HireCType }
     *     
     */
    public void setHire(HireCType value) {
        this.hire = value;
    }

    /**
     * Gets the value of the termination property.
     * 
     * @return
     *     possible object is
     *     {@link TerminationCType }
     *     
     */
    public TerminationCType getTermination() {
        return termination;
    }

    /**
     * Sets the value of the termination property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminationCType }
     *     
     */
    public void setTermination(TerminationCType value) {
        this.termination = value;
    }

    /**
     * Gets the value of the annulation property.
     * 
     * @return
     *     possible object is
     *     {@link AnnulationCType }
     *     
     */
    public AnnulationCType getAnnulation() {
        return annulation;
    }

    /**
     * Sets the value of the annulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnulationCType }
     *     
     */
    public void setAnnulation(AnnulationCType value) {
        this.annulation = value;
    }

    /**
     * Gets the value of the deleteTermination property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteTerminationCType }
     *     
     */
    public DeleteTerminationCType getDeleteTermination() {
        return deleteTermination;
    }

    /**
     * Sets the value of the deleteTermination property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteTerminationCType }
     *     
     */
    public void setDeleteTermination(DeleteTerminationCType value) {
        this.deleteTermination = value;
    }

    /**
     * Gets the value of the changeStudent property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeStudentCType }
     *     
     */
    public ChangeStudentCType getChangeStudent() {
        return changeStudent;
    }

    /**
     * Sets the value of the changeStudent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeStudentCType }
     *     
     */
    public void setChangeStudent(ChangeStudentCType value) {
        this.changeStudent = value;
    }

    /**
     * Gets the value of the changeExtraFlexi property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeExtraFlexiCType }
     *     
     */
    public ChangeExtraFlexiCType getChangeExtraFlexi() {
        return changeExtraFlexi;
    }

    /**
     * Sets the value of the changeExtraFlexi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeExtraFlexiCType }
     *     
     */
    public void setChangeExtraFlexi(ChangeExtraFlexiCType value) {
        this.changeExtraFlexi = value;
    }

}
