//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 10:59:09 AM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v4.hronline;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Scenario to be executed
 * 
 * <p>Java class for ScenarioInfoCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScenarioInfoCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="KeyInfo" type="{}KeyInfoCType"/&gt;
 *         &lt;element name="ScenarioInfoContent" type="{}ScenarioInfoContentCType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScenarioInfoCType", propOrder = {
    "keyInfo",
    "scenarioInfoContent"
})
public class ScenarioInfoCType {

    @XmlElement(name = "KeyInfo", required = true)
    protected KeyInfoCType keyInfo;
    @XmlElement(name = "ScenarioInfoContent", required = true)
    protected ScenarioInfoContentCType scenarioInfoContent;

    /**
     * Gets the value of the keyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link KeyInfoCType }
     *     
     */
    public KeyInfoCType getKeyInfo() {
        return keyInfo;
    }

    /**
     * Sets the value of the keyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyInfoCType }
     *     
     */
    public void setKeyInfo(KeyInfoCType value) {
        this.keyInfo = value;
    }

    /**
     * Gets the value of the scenarioInfoContent property.
     * 
     * @return
     *     possible object is
     *     {@link ScenarioInfoContentCType }
     *     
     */
    public ScenarioInfoContentCType getScenarioInfoContent() {
        return scenarioInfoContent;
    }

    /**
     * Sets the value of the scenarioInfoContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScenarioInfoContentCType }
     *     
     */
    public void setScenarioInfoContent(ScenarioInfoContentCType value) {
        this.scenarioInfoContent = value;
    }

}
