//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 10:59:09 AM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.v4.hronline;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Termination 
 * 
 * <p>Java class for TerminationCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TerminationCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IT0000"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ContractEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TerminationCType", propOrder = {
    "it0000"
})
public class TerminationCType {

    @XmlElement(name = "IT0000", required = true)
    protected TerminationCType.IT0000 it0000;

    /**
     * Gets the value of the it0000 property.
     * 
     * @return
     *     possible object is
     *     {@link TerminationCType.IT0000 }
     *     
     */
    public TerminationCType.IT0000 getIT0000() {
        return it0000;
    }

    /**
     * Sets the value of the it0000 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminationCType.IT0000 }
     *     
     */
    public void setIT0000(TerminationCType.IT0000 value) {
        this.it0000 = value;
    }


    /**
     * Fields for IT0000
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ContractEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contractEndDate"
    })
    public static class IT0000 {

        @XmlElement(name = "ContractEndDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar contractEndDate;

        /**
         * Gets the value of the contractEndDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getContractEndDate() {
            return contractEndDate;
        }

        /**
         * Sets the value of the contractEndDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setContractEndDate(XMLGregorianCalendar value) {
            this.contractEndDate = value;
        }

    }

}
