//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 01:40:01 PM CEST 
//


package be.securex.sss.dimonaconverterservice.xsd.dimonarequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CONTRACT_SOCIALType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CONTRACT_SOCIALType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{}EMPLOYEE_TYPE" minOccurs="0"/&gt;
 *         &lt;element ref="{}SOC_SYS" minOccurs="0"/&gt;
 *         &lt;element ref="{}CAT_SOC_SYS" minOccurs="0"/&gt;
 *         &lt;element ref="{}SUBCAT_SOC_SYS" minOccurs="0"/&gt;
 *         &lt;element ref="{}RSZ_RITME" minOccurs="0"/&gt;
 *         &lt;element ref="{}RSZ_CAT" minOccurs="0"/&gt;
 *         &lt;element ref="{}PLANNED_DAYS_NR" minOccurs="0"/&gt;
 *         &lt;element ref="{}PLANNED_HOURS_NR" minOccurs="0"/&gt;
 *         &lt;element ref="{}HORECA_CONTINGENT_FLAG" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CONTRACT_SOCIALType", propOrder = {

})
public class ContractSocialType {

    @XmlElement(name = "EMPLOYEE_TYPE")
    protected String employeeType;
    @XmlElement(name = "SOC_SYS")
    protected String socSys;
    @XmlElement(name = "CAT_SOC_SYS")
    protected String catSocSys;
    @XmlElement(name = "SUBCAT_SOC_SYS")
    protected String subCatSocSys;
    @XmlElement(name = "RSZ_RITME")
    protected String rszRitme;
    @XmlElement(name = "RSZ_CAT")
    protected String rszCat;
    @XmlElement(name = "PLANNED_DAYS_NR")
    protected String plannedDaysNr;
    @XmlElement(name = "PLANNED_HOURS_NR")
    protected String plannedHoursNr;
    @XmlElement(name = "HORECA_CONTINGENT_FLAG")
    protected String horecaContingentFlag;

    public String getEmployeeType() {
        return employeeType;
    }

    public void setEmployeeType(String employeeType) {
        this.employeeType = employeeType;
    }

    public String getSocSys() {
        return socSys;
    }

    public void setSocSys(String socSys) {
        this.socSys = socSys;
    }

    public String getCatSocSys() {
        return catSocSys;
    }

    public void setCatSocSys(String catSocSys) {
        this.catSocSys = catSocSys;
    }

    public String getSubCatSocSys() {
        return subCatSocSys;
    }

    public void setSubCatSocSys(String subCatSocSys) {
        this.subCatSocSys = subCatSocSys;
    }

    public String getRszRitme() {
        return rszRitme;
    }

    public void setRszRitme(String rszRitme) {
        this.rszRitme = rszRitme;
    }

    public String getRszCat() {
        return rszCat;
    }

    public void setRszCat(String rszCat) {
        this.rszCat = rszCat;
    }

    public String getPlannedDaysNr() {
        return plannedDaysNr;
    }

    public void setPlannedDaysNr(String plannedDaysNr) {
        this.plannedDaysNr = plannedDaysNr;
    }

    public String getPlannedHoursNr() {
        return plannedHoursNr;
    }

    public void setPlannedHoursNr(String plannedHoursNr) {
        this.plannedHoursNr = plannedHoursNr;
    }

    public String getHorecaContingentFlag() {
        return horecaContingentFlag;
    }

    public void setHorecaContingentFlag(String horecaContingentFlag) {
        this.horecaContingentFlag = horecaContingentFlag;
    }
}
