//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 01:40:01 PM CEST 
//


package be.securex.sss.dimonaconverterservice.xsd.dimonarequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DIMONA_DECLARATIONType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DIMONA_DECLARATIONType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}OCCASIONAL_WORKER_TYPE" minOccurs="0"/&gt;
 *         &lt;element ref="{}DECLARATION_TYPE"/&gt;
 *         &lt;element ref="{}DATE_EFF_START_ORIG" minOccurs="0"/&gt;
 *         &lt;element ref="{}DATE_BREACH_ORIG" minOccurs="0"/&gt;
 *         &lt;element ref="{}DATE_FORESEEN_END_ORIG" minOccurs="0"/&gt;
 *         &lt;element ref="{}CONTRACT_NATURE_ORIG" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DIMONA_DECLARATIONType", propOrder = {
    "occasionalWorkerType",
    "declarationType",
    "dateEffStartOrig",
    "dateBreachOrig",
    "dateForeseenEndOrig",
    "contractNatureOrig"
})
public class DimonaDeclarationType {

    @XmlElement(name = "OCCASIONAL_WORKER_TYPE")
    protected String occasionalWorkerType;
    @XmlElement(name = "DECLARATION_TYPE")
    protected int declarationType;
    @XmlElement(name = "DATE_EFF_START_ORIG")
    protected String dateEffStartOrig;
    @XmlElement(name = "DATE_BREACH_ORIG")
    protected String dateBreachOrig;
    @XmlElement(name = "DATE_FORESEEN_END_ORIG")
    protected String dateForeseenEndOrig;
    @XmlElement(name = "CONTRACT_NATURE_ORIG")
    protected String contractNatureOrig;

    public String getOccasionalWorkerType() {
        return occasionalWorkerType;
    }

    public void setOccasionalWorkerType(String occasionalWorkerType) {
        this.occasionalWorkerType = occasionalWorkerType;
    }

    public int getDeclarationType() {
        return declarationType;
    }

    public void setDeclarationType(int declarationType) {
        this.declarationType = declarationType;
    }

    public String getDateEffStartOrig() {
        return dateEffStartOrig;
    }

    public void setDateEffStartOrig(String dateEffStartOrig) {
        this.dateEffStartOrig = dateEffStartOrig;
    }

    public String getDateBreachOrig() {
        return dateBreachOrig;
    }

    public void setDateBreachOrig(String dateBreachOrig) {
        this.dateBreachOrig = dateBreachOrig;
    }

    public String getDateForeseenEndOrig() {
        return dateForeseenEndOrig;
    }

    public void setDateForeseenEndOrig(String dateForeseenEndOrig) {
        this.dateForeseenEndOrig = dateForeseenEndOrig;
    }

    public String getContractNatureOrig() {
        return contractNatureOrig;
    }

    public void setContractNatureOrig(String contractNatureOrig) {
        this.contractNatureOrig = contractNatureOrig;
    }
}
