//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 01:40:01 PM CEST 
//


package be.securex.sss.dimonaconverterservice.xsd.dimonarequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HOURLINEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HOURLINEType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}DATE_START"/&gt;
 *         &lt;element ref="{}TIME_START"/&gt;
 *         &lt;element ref="{}DATE_STOP"/&gt;
 *         &lt;element ref="{}TIME_STOP"/&gt;
 *         &lt;element ref="{}PAUZE"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HOURLINEType", propOrder = {
    "dateStart",
    "timeStart",
    "dateStop",
    "timeStop",
    "pauze"
})
public class HourLineType {

    @XmlElement(name = "DATE_START", required = true)
    protected String dateStart;
    @XmlElement(name = "TIME_START")
    protected int timeStart;
    @XmlElement(name = "DATE_STOP", required = true)
    protected String dateStop;
    @XmlElement(name = "TIME_STOP")
    protected int timeStop;
    @XmlElement(name = "PAUZE", required = true)
    protected String pauze;

    public String getDateStart() {
        return dateStart;
    }

    public void setDateStart(String dateStart) {
        this.dateStart = dateStart;
    }

    public int getTimeStart() {
        return timeStart;
    }

    public void setTimeStart(int timeStart) {
        this.timeStart = timeStart;
    }

    public String getDateStop() {
        return dateStop;
    }

    public void setDateStop(String dateStop) {
        this.dateStop = dateStop;
    }

    public int getTimeStop() {
        return timeStop;
    }

    public void setTimeStop(int timeStop) {
        this.timeStop = timeStop;
    }

    public String getPauze() {
        return pauze;
    }

    public void setPauze(String pauze) {
        this.pauze = pauze;
    }
}
