//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:43:53 PM CET 
//


package be.securex.sss.dimonaconverterservice.xsd.dimonarequest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.securex.sss.dimonaconverterservice.xsd.dimonarequest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ACNR_QNAME = new QName("", "AC_NR");
    private final static QName _BIRTHCOUNTRY_QNAME = new QName("", "BIRTH_COUNTRY");
    private final static QName _BIRTHDATE_QNAME = new QName("", "BIRTH_DATE");
    private final static QName _BIRTHPLACE_QNAME = new QName("", "BIRTH_PLACE");
    private final static QName _BOXNR_QNAME = new QName("", "BOX_NR");
    private final static QName _CATNR_QNAME = new QName("", "CAT_NR");
    private final static QName _CATSOCSYS_QNAME = new QName("", "CAT_SOC_SYS");
    private final static QName _CONTRACTDIMONA_QNAME = new QName("", "CONTRACT_DIMONA");
    private final static QName _CONTRACTNATURE_QNAME = new QName("", "CONTRACT_NATURE");
    private final static QName _CONTRACTNATUREORIG_QNAME = new QName("", "CONTRACT_NATURE_ORIG");
    private final static QName _CONTRACTNUMBER_QNAME = new QName("", "CONTRACT_NUMBER");
    private final static QName _EMPLOYEESTATUTE_QNAME = new QName("", "EMPLOYEE_STATUTE");
    private final static QName _COUNTRY_QNAME = new QName("", "COUNTRY");
    private final static QName _DATEBREACH_QNAME = new QName("", "DATE_BREACH");
    private final static QName _DATEBREACHORIG_QNAME = new QName("", "DATE_BREACH_ORIG");
    private final static QName _DATEEFFSTART_QNAME = new QName("", "DATE_EFF_START");
    private final static QName _DATEEFFSTARTORIG_QNAME = new QName("", "DATE_EFF_START_ORIG");
    private final static QName _DATEFORESEENEND_QNAME = new QName("", "DATE_FORESEEN_END");
    private final static QName _DATEFORESEENENDORIG_QNAME = new QName("", "DATE_FORESEEN_END_ORIG");
    private final static QName _DATESTART_QNAME = new QName("", "DATE_START");
    private final static QName _DATESTOP_QNAME = new QName("", "DATE_STOP");
    private final static QName _PLANNEDDAYSNR_QNAME = new QName("", "PLANNED_DAYS_NR");
    private final static QName _DECLARATIONTYPE_QNAME = new QName("", "DECLARATION_TYPE");
    private final static QName _DEPNR_QNAME = new QName("", "DEP_NR");
    private final static QName _EMAIL_QNAME = new QName("", "EMAIL");
    private final static QName _EMPLOYEETYPE_QNAME = new QName("", "EMPLOYEE_TYPE");
    private final static QName _EXPLCOMPNAME_QNAME = new QName("", "EXPL_COMP_NAME");
    private final static QName _EXPLNR_QNAME = new QName("", "EXPL_NR");
    private final static QName _FAONR_QNAME = new QName("", "FAO_NR");
    private final static QName _FAX_QNAME = new QName("", "FAX");
    private final static QName _FIRMNR_QNAME = new QName("", "FIRM_NR");
    private final static QName _FIRSTNAME_QNAME = new QName("", "FIRST_NAME");
    private final static QName _FULLNAME_QNAME = new QName("", "FULL_NAME");
    private final static QName _GENDER_QNAME = new QName("", "GENDER");
    private final static QName _HERKOMSTTYPE_QNAME = new QName("", "HERKOMST_TYPE");
    private final static QName _HORECACONTINGENTFLAG_QNAME = new QName("", "HORECA_CONTINGENT_FLAG");
    private final static QName _HOUSENR_QNAME = new QName("", "HOUSE_NR");
    private final static QName _LASTNAME_QNAME = new QName("", "LAST_NAME");
    private final static QName _LOCALITY_QNAME = new QName("", "LOCALITY");
    private final static QName _MIDDLEINITIAL_QNAME = new QName("", "MIDDLE_INITIAL");
    private final static QName _NATIONALITY_QNAME = new QName("", "NATIONALITY");
    private final static QName _NUMC32ANEXT_QNAME = new QName("", "NUM_C32A_NEXT");
    private final static QName _NUMC32ASTART_QNAME = new QName("", "NUM_C32A_START");
    private final static QName _NUMNATREG_QNAME = new QName("", "NUM_NAT_REG");
    private final static QName _NUMSISCARD_QNAME = new QName("", "NUM_SIS_CARD");
    private final static QName _OCCASIONALWORKERTYPE_QNAME = new QName("", "OCCASIONAL_WORKER_TYPE");
    private final static QName _PARCOM_QNAME = new QName("", "PAR_COM");
    private final static QName _PAUZE_QNAME = new QName("", "PAUZE");
    private final static QName _REASONENDCONTRACT_QNAME = new QName("", "REASON_END_CONTRACT");
    private final static QName _REF_QNAME = new QName("", "REF");
    private final static QName _RSZCAT_QNAME = new QName("", "RSZ_CAT");
    private final static QName _RSZRITME_QNAME = new QName("", "RSZ_RITME");
    private final static QName _SOCSYS_QNAME = new QName("", "SOC_SYS");
    private final static QName _STREET_QNAME = new QName("", "STREET");
    private final static QName _STREETFULL_QNAME = new QName("", "STREET_FULL");
    private final static QName _COMPLEMENT_QNAME = new QName("", "COMPLEMENT");
    private final static QName _SUBCATSOCSYS_QNAME = new QName("", "SUBCAT_SOC_SYS");
    private final static QName _TEL_QNAME = new QName("", "TEL");
    private final static QName _TIMESTAMP_QNAME = new QName("", "TIMESTAMP");
    private final static QName _TIMESTART_QNAME = new QName("", "TIME_START");
    private final static QName _TIMESTOP_QNAME = new QName("", "TIME_STOP");
    private final static QName _USER_QNAME = new QName("", "USER");
    private final static QName _ZIP_QNAME = new QName("", "ZIP");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.securex.sss.dimonaconverterservice.xsd.dimonarequest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XeiDim }
     * 
     */
    public XeiDim createXEIDIM() {
        return new XeiDim();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link AffiliationType }
     * 
     */
    public AffiliationType createAffiliationType() {
        return new AffiliationType();
    }

    /**
     * Create an instance of {@link ContractType }
     * 
     */
    public ContractType createContractType() {
        return new ContractType();
    }

    /**
     * Create an instance of {@link ContractSocialType }
     * 
     */
    public ContractSocialType createContractSocialType() {
        return new ContractSocialType();
    }

    /**
     * Create an instance of {@link DimonaDeclarationType }
     * 
     */
    public DimonaDeclarationType createDimonaDeclarationType() {
        return new DimonaDeclarationType();
    }

    /**
     * Create an instance of {@link HourLineType }
     * 
     */
    public HourLineType createHourLineType() {
        return new HourLineType();
    }

    /**
     * Create an instance of {@link PayGroupType }
     * 
     */
    public PayGroupType createPayGroupType() {
        return new PayGroupType();
    }

    /**
     * Create an instance of {@link WorkHoursType }
     * 
     */
    public WorkHoursType createWorkHoursType() {
        return new WorkHoursType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AC_NR")
    public JAXBElement<String> createACNR(String value) {
        return new JAXBElement<String>(_ACNR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BIRTH_COUNTRY")
    public JAXBElement<String> createBIRTHCOUNTRY(String value) {
        return new JAXBElement<String>(_BIRTHCOUNTRY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BIRTH_DATE")
    public JAXBElement<String> createBIRTHDATE(String value) {
        return new JAXBElement<String>(_BIRTHDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BIRTH_PLACE")
    public JAXBElement<String> createBIRTHPLACE(String value) {
        return new JAXBElement<String>(_BIRTHPLACE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BOX_NR")
    public JAXBElement<String> createBOXNR(String value) {
        return new JAXBElement<String>(_BOXNR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAT_NR")
    public JAXBElement<String> createCATNR(String value) {
        return new JAXBElement<String>(_CATNR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAT_SOC_SYS")
    public JAXBElement<String> createCATSOCSYS(String value) {
        return new JAXBElement<String>(_CATSOCSYS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CONTRACT_DIMONA")
    public JAXBElement<String> createCONTRACTDIMONA(String value) {
        return new JAXBElement<String>(_CONTRACTDIMONA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CONTRACT_NATURE")
    public JAXBElement<String> createCONTRACTNATURE(String value) {
        return new JAXBElement<String>(_CONTRACTNATURE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CONTRACT_NATURE_ORIG")
    public JAXBElement<String> createCONTRACTNATUREORIG(String value) {
        return new JAXBElement<String>(_CONTRACTNATUREORIG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CONTRACT_NUMBER")
    public JAXBElement<String> createCONTRACTNUMBER(String value) {
        return new JAXBElement<String>(_CONTRACTNUMBER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EMPLOYEE_STATUTE")
    public JAXBElement<String> createEMPLOYEESTATUTE(String value) {
        return new JAXBElement<String>(_EMPLOYEESTATUTE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COUNTRY")
    public JAXBElement<String> createCOUNTRY(String value) {
        return new JAXBElement<String>(_COUNTRY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DATE_BREACH")
    public JAXBElement<String> createDATEBREACH(String value) {
        return new JAXBElement<String>(_DATEBREACH_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DATE_BREACH_ORIG")
    public JAXBElement<String> createDATEBREACHORIG(String value) {
        return new JAXBElement<String>(_DATEBREACHORIG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DATE_EFF_START")
    public JAXBElement<String> createDATEEFFSTART(String value) {
        return new JAXBElement<String>(_DATEEFFSTART_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DATE_EFF_START_ORIG")
    public JAXBElement<String> createDATEEFFSTARTORIG(String value) {
        return new JAXBElement<String>(_DATEEFFSTARTORIG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DATE_FORESEEN_END")
    public JAXBElement<String> createDATEFORESEENEND(String value) {
        return new JAXBElement<String>(_DATEFORESEENEND_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DATE_FORESEEN_END_ORIG")
    public JAXBElement<String> createDATEFORESEENENDORIG(String value) {
        return new JAXBElement<String>(_DATEFORESEENENDORIG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DATE_START")
    public JAXBElement<String> createDATESTART(String value) {
        return new JAXBElement<String>(_DATESTART_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DATE_STOP")
    public JAXBElement<String> createDATESTOP(String value) {
        return new JAXBElement<String>(_DATESTOP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PLANNED_DAYS_NR")
    public JAXBElement<String> createPLANNEDDAYSNR(String value) {
        return new JAXBElement<String>(_PLANNEDDAYSNR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DECLARATION_TYPE")
    public JAXBElement<Integer> createDECLARATIONTYPE(Integer value) {
        return new JAXBElement<Integer>(_DECLARATIONTYPE_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DEP_NR")
    public JAXBElement<String> createDEPNR(String value) {
        return new JAXBElement<String>(_DEPNR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EMAIL")
    public JAXBElement<String> createEMAIL(String value) {
        return new JAXBElement<String>(_EMAIL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EMPLOYEE_TYPE")
    public JAXBElement<String> createEMPLOYEETYPE(String value) {
        return new JAXBElement<String>(_EMPLOYEETYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXPL_COMP_NAME")
    public JAXBElement<String> createEXPLCOMPNAME(String value) {
        return new JAXBElement<String>(_EXPLCOMPNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXPL_NR")
    public JAXBElement<String> createEXPLNR(String value) {
        return new JAXBElement<String>(_EXPLNR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FAO_NR")
    public JAXBElement<String> createFAONR(String value) {
        return new JAXBElement<String>(_FAONR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FAX")
    public JAXBElement<String> createFAX(String value) {
        return new JAXBElement<String>(_FAX_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FIRM_NR")
    public JAXBElement<String> createFIRMNR(String value) {
        return new JAXBElement<String>(_FIRMNR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FIRST_NAME")
    public JAXBElement<String> createFIRSTNAME(String value) {
        return new JAXBElement<String>(_FIRSTNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FULL_NAME")
    public JAXBElement<String> createFULLNAME(String value) {
        return new JAXBElement<String>(_FULLNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GENDER")
    public JAXBElement<String> createGENDER(String value) {
        return new JAXBElement<String>(_GENDER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HERKOMST_TYPE")
    public JAXBElement<Integer> createHERKOMSTTYPE(Integer value) {
        return new JAXBElement<Integer>(_HERKOMSTTYPE_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HORECA_CONTINGENT_FLAG")
    public JAXBElement<String> createHORECACONTINGENTFLAG(String value) {
        return new JAXBElement<String>(_HORECACONTINGENTFLAG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HOUSE_NR")
    public JAXBElement<String> createHOUSENR(String value) {
        return new JAXBElement<String>(_HOUSENR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LAST_NAME")
    public JAXBElement<String> createLASTNAME(String value) {
        return new JAXBElement<String>(_LASTNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LOCALITY")
    public JAXBElement<String> createLOCALITY(String value) {
        return new JAXBElement<String>(_LOCALITY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MIDDLE_INITIAL")
    public JAXBElement<String> createMIDDLEINITIAL(String value) {
        return new JAXBElement<String>(_MIDDLEINITIAL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NATIONALITY")
    public JAXBElement<String> createNATIONALITY(String value) {
        return new JAXBElement<String>(_NATIONALITY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NUM_C32A_NEXT")
    public JAXBElement<String> createNUMC32ANEXT(String value) {
        return new JAXBElement<String>(_NUMC32ANEXT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NUM_C32A_START")
    public JAXBElement<String> createNUMC32ASTART(String value) {
        return new JAXBElement<String>(_NUMC32ASTART_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NUM_NAT_REG")
    public JAXBElement<String> createNUMNATREG(String value) {
        return new JAXBElement<String>(_NUMNATREG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NUM_SIS_CARD")
    public JAXBElement<String> createNUMSISCARD(String value) {
        return new JAXBElement<String>(_NUMSISCARD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OCCASIONAL_WORKER_TYPE")
    public JAXBElement<String> createOCCASIONALWORKERTYPE(String value) {
        return new JAXBElement<String>(_OCCASIONALWORKERTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PAR_COM")
    public JAXBElement<String> createPARCOM(String value) {
        return new JAXBElement<String>(_PARCOM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PAUZE")
    public JAXBElement<String> createPAUZE(String value) {
        return new JAXBElement<String>(_PAUZE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REASON_END_CONTRACT")
    public JAXBElement<String> createREASONENDCONTRACT(String value) {
        return new JAXBElement<String>(_REASONENDCONTRACT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REF")
    public JAXBElement<String> createREF(String value) {
        return new JAXBElement<String>(_REF_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RSZ_CAT")
    public JAXBElement<String> createRSZCAT(String value) {
        return new JAXBElement<String>(_RSZCAT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RSZ_RITME")
    public JAXBElement<String> createRSZRITME(String value) {
        return new JAXBElement<String>(_RSZRITME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SOC_SYS")
    public JAXBElement<String> createSOCSYS(String value) {
        return new JAXBElement<String>(_SOCSYS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STREET")
    public JAXBElement<String> createSTREET(String value) {
        return new JAXBElement<String>(_STREET_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STREET_FULL")
    public JAXBElement<String> createSTREETFULL(String value) {
        return new JAXBElement<String>(_STREETFULL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COMPLEMENT")
    public JAXBElement<String> createCOMPLEMENT(String value) {
        return new JAXBElement<String>(_COMPLEMENT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SUBCAT_SOC_SYS")
    public JAXBElement<String> createSUBCATSOCSYS(String value) {
        return new JAXBElement<String>(_SUBCATSOCSYS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEL")
    public JAXBElement<String> createTEL(String value) {
        return new JAXBElement<String>(_TEL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIMESTAMP")
    public JAXBElement<String> createTIMESTAMP(String value) {
        return new JAXBElement<String>(_TIMESTAMP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIME_START")
    public JAXBElement<Integer> createTIMESTART(Integer value) {
        return new JAXBElement<Integer>(_TIMESTART_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIME_STOP")
    public JAXBElement<Integer> createTIMESTOP(Integer value) {
        return new JAXBElement<Integer>(_TIMESTOP_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "USER")
    public JAXBElement<String> createUSER(String value) {
        return new JAXBElement<String>(_USER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ZIP")
    public JAXBElement<String> createZIP(String value) {
        return new JAXBElement<String>(_ZIP_QNAME, String.class, null, value);
    }

}
