//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 01:40:01 PM CEST 
//


package be.securex.sss.dimonaconverterservice.xsd.dimonarequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PAYGROUPType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PAYGROUPType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}FIRM_NR"/&gt;
 *         &lt;element ref="{}DEP_NR" minOccurs="0"/&gt;
 *         &lt;element ref="{}CAT_NR" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PAYGROUPType", propOrder = {
    "firmNr",
    "depNr",
    "catNr"
})
public class PayGroupType {

    @XmlElement(name = "FIRM_NR", required = true)
    protected String firmNr;
    @XmlElement(name = "DEP_NR")
    protected String depNr;
    @XmlElement(name = "CAT_NR")
    protected String catNr;

    public String getFirmNr() {
        return firmNr;
    }

    public void setFirmNr(String firmNr) {
        this.firmNr = firmNr;
    }

    public String getDepNr() {
        return depNr;
    }

    public void setDepNr(String depNr) {
        this.depNr = depNr;
    }

    public String getCatNr() {
        return catNr;
    }

    public void setCatNr(String catNr) {
        this.catNr = catNr;
    }
}
