//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 01:40:01 PM CEST 
//


package be.securex.sss.dimonaconverterservice.xsd.dimonarequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PERSONType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PERSONType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{}FULL_NAME" minOccurs="0"/&gt;
 *         &lt;element ref="{}LAST_NAME" minOccurs="0"/&gt;
 *         &lt;element ref="{}FIRST_NAME" minOccurs="0"/&gt;
 *         &lt;element ref="{}MIDDLE_INITIAL" minOccurs="0"/&gt;
 *         &lt;element ref="{}GENDER" minOccurs="0"/&gt;
 *         &lt;element ref="{}NATIONALITY" minOccurs="0"/&gt;
 *         &lt;element ref="{}BIRTH_DATE" minOccurs="0"/&gt;
 *         &lt;element ref="{}BIRTH_COUNTRY" minOccurs="0"/&gt;
 *         &lt;element ref="{}BIRTH_PLACE" minOccurs="0"/&gt;
 *         &lt;element ref="{}NUM_NAT_REG" minOccurs="0"/&gt;
 *         &lt;element name="SAP_PERNR" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{}NUM_SIS_CARD" minOccurs="0"/&gt;
 *         &lt;element name="ADDRESS" type="{}ADDRESSType" minOccurs="0"/&gt;
 *         &lt;element name="CONTRACT" type="{}CONTRACTType"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PERSONType", propOrder = {

})
public class PersonType {

    @XmlElement(name = "FULL_NAME")
    protected String fullName;
    @XmlElement(name = "LAST_NAME")
    protected String lastName;
    @XmlElement(name = "FIRST_NAME")
    protected String firstName;
    @XmlElement(name = "MIDDLE_INITIAL")
    protected String middleInitial;
    @XmlElement(name = "GENDER")
    protected String gender;
    @XmlElement(name = "NATIONALITY")
    protected String nationality;
    @XmlElement(name = "BIRTH_DATE")
    protected String birthDate;
    @XmlElement(name = "BIRTH_COUNTRY")
    protected String birthCountry;
    @XmlElement(name = "BIRTH_PLACE")
    protected String birthPlace;
    @XmlElement(name = "NUM_NAT_REG")
    protected String numNatReg;
    @XmlElement(name = "SAP_PERNR")
    protected String sapPerNr;
    @XmlElement(name = "NUM_SIS_CARD")
    protected String numSisCard;
    @XmlElement(name = "ADDRESS")
    protected AddressType address;
    @XmlElement(name = "CONTRACT", required = true)
    protected ContractType contract;

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getMiddleInitial() {
        return middleInitial;
    }

    public void setMiddleInitial(String middleInitial) {
        this.middleInitial = middleInitial;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getNationality() {
        return nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    public String getBirthCountry() {
        return birthCountry;
    }

    public void setBirthCountry(String birthCountry) {
        this.birthCountry = birthCountry;
    }

    public String getBirthPlace() {
        return birthPlace;
    }

    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }

    public String getNumNatReg() {
        return numNatReg;
    }

    public void setNumNatReg(String numNatReg) {
        this.numNatReg = numNatReg;
    }

    public String getSapPerNr() {
        return sapPerNr;
    }

    public void setSapPerNr(String sapPerNr) {
        this.sapPerNr = sapPerNr;
    }

    public String getNumSisCard() {
        return numSisCard;
    }

    public void setNumSisCard(String numSisCard) {
        this.numSisCard = numSisCard;
    }

    public AddressType getAddress() {
        return address;
    }

    public void setAddress(AddressType address) {
        this.address = address;
    }

    public ContractType getContract() {
        return contract;
    }

    public void setContract(ContractType contract) {
        this.contract = contract;
    }
}
