//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 01:40:01 PM CEST 
//


package be.securex.sss.dimonaconverterservice.xsd.dimonarequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}REF" minOccurs="0"/&gt;
 *         &lt;element name="ORIGIN_EUHREKA" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element ref="{}EMAIL" minOccurs="0"/&gt;
 *         &lt;element name="PAYMENT_TYPE" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="\d*"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PERSON" type="{}PERSONType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ref",
    "originEuhreka",
    "email",
    "paymentType",
    "person"
})
@XmlRootElement(name = "XEI_DIM")
public class XeiDim {

    @XmlElement(name = "REF")
    protected String ref;
    @XmlElement(name = "ORIGIN_EUHREKA")
    protected Boolean originEuhreka;
    @XmlElement(name = "EMAIL")
    protected String email;
    @XmlElement(name = "PAYMENT_TYPE")
    protected String paymentType;
    @XmlElement(name = "PERSON", required = true)
    protected PersonType person;

    public String getRef() {
        return ref;
    }

    public void setRef(String ref) {
        this.ref = ref;
    }

    public Boolean getOriginEuhreka() {
        return originEuhreka;
    }

    public void setOriginEuhreka(Boolean originEuhreka) {
        this.originEuhreka = originEuhreka;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPaymentType() {
        return paymentType;
    }

    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    public PersonType getPerson() {
        return person;
    }

    public void setPerson(PersonType person) {
        this.person = person;
    }
}
